// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AddTaskInterface is an autogenerated mock type for the AddTaskInterface type
type AddTaskInterface struct {
	mock.Mock
}

// AddNewTask provides a mock function with given fields: username, note, importance
func (_m *AddTaskInterface) AddNewTask(username string, note string, importance int) (bool, error) {
	ret := _m.Called(username, note, importance)

	if len(ret) == 0 {
		panic("no return value specified for AddNewTask")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) (bool, error)); ok {
		return rf(username, note, importance)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) bool); ok {
		r0 = rf(username, note, importance)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(username, note, importance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddTaskInterface creates a new instance of AddTaskInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddTaskInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddTaskInterface {
	mock := &AddTaskInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
